# Generated by Django 4.2.5 on 2023-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserRequest', models.TextField()),
                ('planetIndex', models.IntegerField()),
                ('educationIndex', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GPTResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.CharField(max_length=1000)),
            ],
        ),
    ]
